# Generated by Django 6.0.1 on 2026-03-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("designation", models.CharField(max_length=255)),
                ("representation", models.CharField(max_length=255)),
                ("quantite_disponible", models.PositiveIntegerField(default=0)),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
