# Generated by Codex on 2026-03-17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="categorie",
            field=models.CharField(
                choices=[("homme", "Homme"), ("femme", "Femme"), ("enfant", "Enfant")],
                default="homme",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="date_ajout",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
